version: 2
builds:
  - id: abcd-lite
    binary: abcd-lite
    tags:
      - production
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/1k-off/abcd-lite/internal/config.keygenAccount={{ .Env.KEYGEN_ACCOUNT }}
      - -X github.com/1k-off/abcd-lite/internal/config.keygenProduct={{ .Env.KEYGEN_PRODUCT }}
      - -X github.com/1k-off/abcd-lite/internal/config.keygenPublicKey={{ .Env.KEYGEN_PUBLIC_KEY }}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE.md
      - README.md

release:
  prerelease: auto
