name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    if: github.repository == '1k-off/abcd-lite'
    runs-on: ubuntu-latest
    steps:
      - name: Set current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: actions/setup-node@v4
        id: node
        with:
          node-version: 22

      - name: Build Frontend
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
        working-directory: frontend
        
      - name: Cache GeoIP Database
        id: geoip-cache
        uses: actions/cache@v4
        with:
          path: data/geo/GeoLite2-Country.mmdb
          key: geoip-${{ runner.os }}-${{ steps.date.outputs.date }}

      - name: Download GeoIP Database
        if: steps.geoip-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p data/geo
          cd data/geo
          wget --content-disposition --user=${{ secrets.MAXMIND_USERNAME }} --password=${{ secrets.MAXMIND_PASSWORD }} -O GeoLite2-Country.tar.gz 'https://download.maxmind.com/geoip/databases/GeoLite2-Country/download?suffix=tar.gz'
          tar -xzf GeoLite2-Country.tar.gz
          rm GeoLite2-Country.tar.gz
          mv GeoLite2-Country_*/GeoLite2-Country.mmdb .
          rm -rf GeoLite2-Country_*

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYGEN_ACCOUNT: ${{ secrets.KEYGEN_ACCOUNT }}
          KEYGEN_PRODUCT: ${{ secrets.KEYGEN_PRODUCT }}
          KEYGEN_PUBLIC_KEY: ${{ secrets.KEYGEN_PUBLIC_KEY }}
